name: eloqua
description: Eloqua Speech Coaching App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  file_picker: ^8.1.2
  http: ^1.2.2
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  fl_chart: ^0.68.0
  shared_preferences: ^2.3.2
  vibration: ^2.0.0
  flutter_tts: ^4.0.2
  speech_to_text: ^7.3.0
  qr_flutter: ^4.1.0
  path_provider: ^2.1.4
  share_plus: ^10.1.4
  syncfusion_flutter_pdf: ^26.2.14
  video_player: ^2.8.3
  saver_gallery: ^3.0.6
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
